// Code generated by protoc-gen-go.
// source: project.proto
// DO NOT EDIT!

/*
Package project is a generated protocol buffer package.

It is generated from these files:
	project.proto

It has these top-level messages:
	Project
	CreateRequest
	CreateReply
	DeleteRequest
	DeleteReply
*/
package project

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Project struct {
	RepoId    int32  `protobuf:"varint,1,opt,name=repo_id,json=repoId" json:"repo_id,omitempty"`
	OwnerName string `protobuf:"bytes,2,opt,name=owner_name,json=ownerName" json:"owner_name,omitempty"`
	RepoName  string `protobuf:"bytes,3,opt,name=repo_name,json=repoName" json:"repo_name,omitempty"`
	Token     string `protobuf:"bytes,4,opt,name=token" json:"token,omitempty"`
}

func (m *Project) Reset()                    { *m = Project{} }
func (m *Project) String() string            { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()               {}
func (*Project) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CreateRequest struct {
	Project *Project `protobuf:"bytes,1,opt,name=project" json:"project,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateRequest) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type CreateReply struct {
	Project *Project `protobuf:"bytes,1,opt,name=project" json:"project,omitempty"`
}

func (m *CreateReply) Reset()                    { *m = CreateReply{} }
func (m *CreateReply) String() string            { return proto.CompactTextString(m) }
func (*CreateReply) ProtoMessage()               {}
func (*CreateReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateReply) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type DeleteRequest struct {
	RepoId int32 `protobuf:"varint,1,opt,name=repo_id,json=repoId" json:"repo_id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type DeleteReply struct {
	Project *Project `protobuf:"bytes,1,opt,name=project" json:"project,omitempty"`
}

func (m *DeleteReply) Reset()                    { *m = DeleteReply{} }
func (m *DeleteReply) String() string            { return proto.CompactTextString(m) }
func (*DeleteReply) ProtoMessage()               {}
func (*DeleteReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DeleteReply) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

func init() {
	proto.RegisterType((*Project)(nil), "project.Project")
	proto.RegisterType((*CreateRequest)(nil), "project.CreateRequest")
	proto.RegisterType((*CreateReply)(nil), "project.CreateReply")
	proto.RegisterType((*DeleteRequest)(nil), "project.DeleteRequest")
	proto.RegisterType((*DeleteReply)(nil), "project.DeleteReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for ProjectSvc service

type ProjectSvcClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateReply, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteReply, error)
}

type projectSvcClient struct {
	cc *grpc.ClientConn
}

func NewProjectSvcClient(cc *grpc.ClientConn) ProjectSvcClient {
	return &projectSvcClient{cc}
}

func (c *projectSvcClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateReply, error) {
	out := new(CreateReply)
	err := grpc.Invoke(ctx, "/project.ProjectSvc/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectSvcClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteReply, error) {
	out := new(DeleteReply)
	err := grpc.Invoke(ctx, "/project.ProjectSvc/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ProjectSvc service

type ProjectSvcServer interface {
	Create(context.Context, *CreateRequest) (*CreateReply, error)
	Delete(context.Context, *DeleteRequest) (*DeleteReply, error)
}

func RegisterProjectSvcServer(s *grpc.Server, srv ProjectSvcServer) {
	s.RegisterService(&_ProjectSvc_serviceDesc, srv)
}

func _ProjectSvc_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectSvcServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.ProjectSvc/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectSvcServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectSvc_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectSvcServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.ProjectSvc/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectSvcServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProjectSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "project.ProjectSvc",
	HandlerType: (*ProjectSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ProjectSvc_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ProjectSvc_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("project.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x28, 0xca, 0xcf,
	0x4a, 0x4d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x4a, 0xb8,
	0xd8, 0x03, 0x20, 0x4c, 0x21, 0x71, 0x2e, 0xf6, 0xa2, 0xd4, 0x82, 0xfc, 0xf8, 0xcc, 0x14, 0x09,
	0x46, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x36, 0x10, 0xd7, 0x33, 0x45, 0x48, 0x96, 0x8b, 0x2b, 0xbf,
	0x3c, 0x2f, 0xb5, 0x28, 0x3e, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x49, 0x81, 0x51, 0x83, 0x33, 0x88,
	0x13, 0x2c, 0xe2, 0x97, 0x98, 0x9b, 0x2a, 0x24, 0xcd, 0xc5, 0x09, 0xd6, 0x07, 0x96, 0x65, 0x06,
	0xcb, 0x72, 0x80, 0x04, 0xc0, 0x92, 0x22, 0x5c, 0xac, 0x25, 0xf9, 0xd9, 0xa9, 0x79, 0x12, 0x2c,
	0x60, 0x09, 0x08, 0x47, 0xc9, 0x9a, 0x8b, 0xd7, 0xb9, 0x28, 0x35, 0xb1, 0x24, 0x35, 0x28, 0xb5,
	0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x48, 0x8b, 0x0b, 0xe6, 0x22, 0xb0, 0xdd, 0xdc, 0x46, 0x02, 0x7a,
	0x30, 0x07, 0x43, 0x9d, 0x17, 0x04, 0x77, 0xb2, 0x25, 0x17, 0x37, 0x4c, 0x73, 0x41, 0x4e, 0x25,
	0x49, 0x5a, 0x35, 0xb8, 0x78, 0x5d, 0x52, 0x73, 0x52, 0x11, 0xf6, 0xe2, 0xf2, 0x33, 0xc8, 0x12,
	0x98, 0x4a, 0x12, 0x2d, 0x31, 0x6a, 0x60, 0xe4, 0xe2, 0x82, 0x0a, 0x06, 0x97, 0x25, 0x0b, 0x59,
	0x70, 0xb1, 0x41, 0x9c, 0x2b, 0x24, 0x06, 0xd7, 0x83, 0xe2, 0x79, 0x29, 0x11, 0x0c, 0xf1, 0x82,
	0x9c, 0x4a, 0x25, 0x06, 0x90, 0x4e, 0x88, 0x1b, 0x90, 0x74, 0xa2, 0x38, 0x1f, 0x49, 0x27, 0x92,
	0x63, 0x95, 0x18, 0x92, 0xd8, 0xc0, 0xb1, 0x6c, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x93, 0x15,
	0x55, 0xad, 0xf6, 0x01, 0x00, 0x00,
}
